### ISSUE TITLE
Add chapter for JavaScript

### ISSUE THREAD

**Issue by ODXT** [devRant-Squad/Community-Programming-Book#12]
Create chapter for JavaScript. Instructions are in repo.

**Comment by gadilashashank** [comment]
Anyone doing this? I can take it up now

**Comment by FilipeRamalho** [comment]
Yes @RootPixl wanted to do that

**Comment by RootPixl** [comment]
Yes, I pushed to master intro.md for JS.

**Comment by FilipeRamalho** [comment]
@RootPixl you have to make a PR and also do a Readme.md, please read the Contributing.md

**Comment by FilipeRamalho** [comment]
@RootPixl Can you confirm you have saved it somewhere else, so I can revert to the last commit you can fork add the changes and the PR.

**Comment by RootPixl** [comment]
@FilipeRamalho okay, I'll add Readme.md
And yes, you can revert that, I have a backup on my laptop

**Comment by FilipeRamalho** [comment]
#21 solves this
