### ISSUE TITLE
Create credit page

### ISSUE THREAD

**Issue by ODXT** [devRant-Squad/Community-Programming-Book#18]
Add devRant usernames, possibly attached with GitHub names, into a list. To be added at the end of book to be credited.

**Comment by FilipeRamalho** [comment]
Should I make one with all that have till this moment have commited something and @Parou for the art work ?

**Comment by ODXT** [comment]
Yes, we can always modify it later.

**Comment by FilipeRamalho** [comment]
https://github.com/devRant-Squad/Community-Programming-Book/commit/f928c77ed5abc1c3cb757b000e0ecddcd8a95252 adds a credit page.
