### ISSUE TITLE
Name of author 

### ISSUE THREAD

**Issue by gadilashashank** [devRant-Squad/Community-Programming-Book#24]
I'd like to propose to add the name of the author in the file README.md for each chapter. A sample is given below. Another related proposal is to add the members of each team in the credits page. These measures would ensure the contribution of each individual is given due credit. 
# Chapter name 
> This chapter has been authored by X.

Some introduction

**Comment by FilipeRamalho** [comment]
https://github.com/devRant-Squad/Community-Programming-Book/commit/3da2d66ed164b155ac3f00454abb3efe97e08ba8
adds that suggestion
