### ISSUE TITLE
Create editing team

### ISSUE THREAD

**Issue by ODXT** [devRant-Squad/Community-Programming-Book#9]
Gather individuals with an understanding in English, to build an editing team.

Responsibilities:
+ Review PR's 
+ Ensure tone, grammar, and consistentcy
+ Validate statements

(Obviously, editors that are also writers will NOT review their own work)

**Comment by ODXT** [comment]
@FilipeRamalho, correct me if I'm wrong, but I believe you had requested to review the chapters. If so, would you be willing to join the editing team?

Additionally, I recommend Michelle for this team.

**Comment by FilipeRamalho** [comment]
@ODXT I would join, but I would rather only review content and Styling, I wouldn't put too much trust in my Grammar abilities, they aren't bad, but not good enough for reviewing.

**Comment by ODXT** [comment]
Ok, I think we would assign this to the team, not an individual. So you could approve the content and style. Then let someone else approve the grammar. I can validate the facts and dates.

**Comment by Skayo** [comment]
Created the team.

**Comment by Skayo** [comment]
I will help where ever I can! Not a native speaker but I'll do my best

**Comment by FilipeRamalho** [comment]
@devRant-Squad/editors @ODXT @Skayo Do you think there are enough in the edit team ?

**Comment by Skayo** [comment]
@FilipeRamalho In ratio to the amount of writers, there are definitely enough.

**Comment by FilipeRamalho** [comment]
Closed, if more editors are needed it can be reopen.
